# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/MULT_16X16/MULT_16X16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MULT_16X16 || ORIG_REF_NAME==MULT_16X16} -quiet] -quiet

# IP: ip/IN_FEA_BRAM/IN_FEA_BRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IN_FEA_BRAM || ORIG_REF_NAME==IN_FEA_BRAM} -quiet] -quiet
