# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: b:/wd/Huabei/Huabei/Jingjinhai_Army/Huabei_JJH_Ar/Huabei_JJH_Ar.srcs/sources_1/ip/MATRIX_ABC_ROM/MATRIX_ABC_ROM.xci
# IP: The module: 'MATRIX_ABC_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: b:/wd/Huabei/Huabei/Jingjinhai_Army/Huabei_JJH_Ar/Huabei_JJH_Ar.srcs/sources_1/ip/MATRIX_ABC_ROM/MATRIX_ABC_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MATRIX_ABC_ROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: b:/wd/Huabei/Huabei/Jingjinhai_Army/Huabei_JJH_Ar/Huabei_JJH_Ar.srcs/sources_1/ip/MATRIX_ABC_ROM/MATRIX_ABC_ROM.xci
# IP: The module: 'MATRIX_ABC_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: b:/wd/Huabei/Huabei/Jingjinhai_Army/Huabei_JJH_Ar/Huabei_JJH_Ar.srcs/sources_1/ip/MATRIX_ABC_ROM/MATRIX_ABC_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MATRIX_ABC_ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
