# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: B:/wd/Huabei/Huabei/Jingjinhai_Army/Huabei_JJH_Ar/Huabei_JJH_Ar.srcs/sources_1/ip/CONV1_WEI_64BX3X3/CONV1_WEI_64BX3X3.xci
# IP: The module: 'CONV1_WEI_64BX3X3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: b:/wd/Huabei/Huabei/Jingjinhai_Army/Huabei_JJH_Ar/Huabei_JJH_Ar.srcs/sources_1/ip/CONV1_WEI_64BX3X3/CONV1_WEI_64BX3X3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CONV1_WEI_64BX3X3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: B:/wd/Huabei/Huabei/Jingjinhai_Army/Huabei_JJH_Ar/Huabei_JJH_Ar.srcs/sources_1/ip/CONV1_WEI_64BX3X3/CONV1_WEI_64BX3X3.xci
# IP: The module: 'CONV1_WEI_64BX3X3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: b:/wd/Huabei/Huabei/Jingjinhai_Army/Huabei_JJH_Ar/Huabei_JJH_Ar.srcs/sources_1/ip/CONV1_WEI_64BX3X3/CONV1_WEI_64BX3X3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CONV1_WEI_64BX3X3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
