# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: b:/wd/Huabei/Huabei/Jingjinhai_Army/Huabei_JJH_Ar/Huabei_JJH_Ar.srcs/sources_1/ip/ADDER_16P16/ADDER_16P16.xci
# IP: The module: 'ADDER_16P16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: b:/wd/Huabei/Huabei/Jingjinhai_Army/Huabei_JJH_Ar/Huabei_JJH_Ar.srcs/sources_1/ip/ADDER_16P16/ADDER_16P16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADDER_16P16'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: b:/wd/Huabei/Huabei/Jingjinhai_Army/Huabei_JJH_Ar/Huabei_JJH_Ar.srcs/sources_1/ip/ADDER_16P16/ADDER_16P16.xci
# IP: The module: 'ADDER_16P16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: b:/wd/Huabei/Huabei/Jingjinhai_Army/Huabei_JJH_Ar/Huabei_JJH_Ar.srcs/sources_1/ip/ADDER_16P16/ADDER_16P16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADDER_16P16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
