# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: b:/wd/Huabei/Huabei/Jingjinhai_Army/Huabei_JJH_Ar/Huabei_JJH_Ar.srcs/sources_1/ip/BN_PARA_64CHN/BN_PARA_64CHN.xci
# IP: The module: 'BN_PARA_64CHN' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: b:/wd/Huabei/Huabei/Jingjinhai_Army/Huabei_JJH_Ar/Huabei_JJH_Ar.srcs/sources_1/ip/BN_PARA_64CHN/BN_PARA_64CHN_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BN_PARA_64CHN'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: b:/wd/Huabei/Huabei/Jingjinhai_Army/Huabei_JJH_Ar/Huabei_JJH_Ar.srcs/sources_1/ip/BN_PARA_64CHN/BN_PARA_64CHN.xci
# IP: The module: 'BN_PARA_64CHN' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: b:/wd/Huabei/Huabei/Jingjinhai_Army/Huabei_JJH_Ar/Huabei_JJH_Ar.srcs/sources_1/ip/BN_PARA_64CHN/BN_PARA_64CHN_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BN_PARA_64CHN'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
