# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: b:/wd/Huabei/Huabei/Jingjinhai_Army/Huabei_JJH_Ar/Huabei_JJH_Ar.srcs/sources_1/ip/fifo_32bx4/fifo_32bx4.xci
# IP: The module: 'fifo_32bx4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: b:/wd/Huabei/Huabei/Jingjinhai_Army/Huabei_JJH_Ar/Huabei_JJH_Ar.srcs/sources_1/ip/fifo_32bx4/fifo_32bx4.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_32bx4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: b:/wd/Huabei/Huabei/Jingjinhai_Army/Huabei_JJH_Ar/Huabei_JJH_Ar.srcs/sources_1/ip/fifo_32bx4/fifo_32bx4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_32bx4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: b:/wd/Huabei/Huabei/Jingjinhai_Army/Huabei_JJH_Ar/Huabei_JJH_Ar.srcs/sources_1/ip/fifo_32bx4/fifo_32bx4.xci
# IP: The module: 'fifo_32bx4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: b:/wd/Huabei/Huabei/Jingjinhai_Army/Huabei_JJH_Ar/Huabei_JJH_Ar.srcs/sources_1/ip/fifo_32bx4/fifo_32bx4.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_32bx4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: b:/wd/Huabei/Huabei/Jingjinhai_Army/Huabei_JJH_Ar/Huabei_JJH_Ar.srcs/sources_1/ip/fifo_32bx4/fifo_32bx4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_32bx4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
